# Generated by Django 4.1.3 on 2022-11-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='spicy_level',
            field=models.IntegerField(default=0, verbose_name=range(0, 5)),
        ),
    ]
