# Generated by Django 4.1.3 on 2022-11-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_menu_item_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_item',
            new_name='MenuItem',
        ),
    ]
