# Generated by Django 4.1.3 on 2022-11-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_menu_item_spicy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='spicy_level',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=255),
        ),
    ]
